name: FTP Deployment

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install lftp -y

      - name: Deploy via FTP (with hardcoded credentials)
        run: |
          FTP_USERNAME="ithubQbank@qbank.c1.is"
          FTP_PASSWORD="Bja26@gmail"
          FTP_SERVER="qbank.c1.is"
          REMOTE_PATH="/home/qbankcis/domains/qbank.c1.is"

          lftp -e "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -R -e -x .git -x .github -x .gitignore -x .gitattributes . $REMOTE_PATH; exit"
