name: FTP Deployment

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install lftp -y

      - name: Deploy via FTP (without SITE SYMLINK)
        run: |
          FTP_SERVER="qbank.c1.is"
          FTP_USERNAME="GitHubQbank@qbank.c1.is"
          FTP_PASSWORD="Bja26@gmail"

          lftp -e "set ftp:ssl-allow no; set ftp:passive-mode true; set ftp:sync-mode off; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER && mirror -R -e -x .gitignore -x .github -x .git -x .gitattributes / /home/qbankcis/domains/qbank.c1.is"