name: FTP Deployment

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install lftp -y

      - name: Deploy via FTP (without SSL verification)
        run: |
          FTP_USERNAME="qbankcis"
          FTP_PASSWORD="j@6p!3GJ6CaW8d"
          FTP_SERVER="ftp.qbank.c1.is"
          REMOTE_PATH="/home/qbankcis/"

          lftp -e "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD -p 21 $FTP_SERVER; mirror -R -e -x .git -x .github -x .gitignore -x .gitattributes . $REMOTE_PATH; exit"